data_directory: data/inputs/5083_P2_o6_h3_sensor_data
model_order: ["DCRNN"]
models:
  Constant: {}
  SeasonalNaive:
    seasonality: 252
  DCRNN:
    config_filename: "data/test/test.yaml"
    output_filename: "data/test/test.out"
    predictions_filename: "data/test/predictions.npz"
#  DCRNN:
#    config_filename: "data/5083_P1/5083_P1.yaml"
#    output_filename: "data/5083_P1/5083_P1.out"
#    predictions_filename: "data/5083_P1/predictions.npz"
