data_directory: data/inputs/5083/5083_${plan}_o${offset}_h6_sb${offset}_sensor_data
loop:
  values:
    plan: ["P2"]
    offset: [3, 6]
  keys: ["data_directory", "models/DCRNN/base_dir"]
model_order: ["DCRNN"]
models:
  DCRNN:
    base_dir: "data/test/5083_${plan}_o${offset}_h6_sb${offset}"
    calculate_train_and_val_errors: False
