data_directory: data/inputs/5083/5083_${plan}_o${offset}_h6_sb${offset}_sensor_data
loop:
  values:
    plan: ["P1", "P2", "P3"]
    offset: [3, 6, 12, 24]
  parallel: ["plan", "offset"]
  keys: ["data_directory", "models/DCRNN/base_dir"]
model_order: ["DCRNN"]
models:
  DCRNN:
    base_dir: "data/test_diag_2/5083_${plan}_o${offset}_h6_sb${offset}"
