data_directory: data/inputs/5083/5083_P3_o${offset}_h6_sb${offset}_sensor_data
loop:
  values:
    offset: [3, 6, 12, 24]
  parallel: ["offset"]
  keys: ["data_directory", "models/DCRNN/base_dir"]
model_order: ["DCRNN"]
models:
  DCRNN:
    base_dir: "data/test_std1_2/5083_P3_o${offset}_h6_sb${offset}"
